export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const LOADING = "LOADING";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_ALL_TO_CART = "ADD_ALL_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART = "UPDATE_CART";
